apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: university-app
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.postgresDb | quote }}
  STUDENT_DB_USER: {{ .Values.postgres.auth.studentDbUser | quote }}
  STUDENT_DB_PASSWORD: {{ .Values.postgres.auth.studentDbPassword | quote }}
  TEACHER_ADMIN_DB_USER: {{ .Values.postgres.auth.teacherAdminDbUser | quote }}
  TEACHER_ADMIN_DB_PASSWORD: {{ .Values.postgres.auth.teacherAdminDbPassword | quote }}
  ENROLLMENT_DB_USER: {{ .Values.postgres.auth.enrollmentDbUser | quote }}
  ENROLLMENT_DB_PASSWORD: {{ .Values.postgres.auth.enrollmentDbPassword | quote }}
