apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: university-app
spec:
  clusterIP: None  # Headless : identité réseau stable requise par le StatefulSet
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
