apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-students
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - /api/students

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-teachers
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - /api/teachers

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-enrollments
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - /api/enrollments